use_frameworks!
platform :ios,'8.0'
inhibit_all_warnings!

target 'GMVideoEffectDemo' do
    # Pods for GMVideoEffectDemo
  
    pod 'SDWebImage'
    pod 'YYKit'
    #pod 'SDCycleScrollView'
    pod 'Masonry'
    pod 'JSONModel'
    pod 'MJRefresh'
    pod 'MMPopupView'
    pod 'MBProgressHUD'
    pod 'MobileVLCKit'
    pod 'Bugly'
    
    target 'GMVideoEffectDemoTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'GMVideoEffectDemoUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end

